# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CreateCirc2
                                 A QGIS plugin
 Create circle base on center (latitdue, longitude or bearing and distance against point) and radius
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-12-08
        copyright            : (C) 2018 by Paweł Strzelewicz
        email                : @
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CreateCirc2 class from file CreateCirc2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .create_circ2 import CreateCirc2
    return CreateCirc2(iface)
