# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CreateCirc2
                                 A QGIS plugin
 Create circle base on center (latitdue, longitude or bearing and distance against point) and radius
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-12-08
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Paweł Strzelewicz
        email                : aviationgisapp@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, QVariant
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction, QMessageBox, QWidget
from qgis.core import *


# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .create_circ2_dialog import CreateCirc2Dialog
import os.path

from . import circ_tools as ct

w = QWidget()


class CreateCirc2:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        self.circ_center = None
        self.radius_m = None
        self.polygon_name = ''
        self.mlyr_name = ''

        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'CreateCirc2_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Create the dialog (after translation) and keep reference
        self.dlg = CreateCirc2Dialog()

        self.dlg.checkBoxCenterDef.stateChanged.connect(self.circ_center_def)
        self.dlg.pushButtonAddCircle.clicked.connect(self.add_circle)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&CreateCircle2')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'CreateCirc2')
        self.toolbar.setObjectName(u'CreateCirc2')

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('CreateCirc2', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/create_circ2/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'CreateCircle2'),
            callback=self.run,
            parent=self.iface.mainWindow())

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&CreateCircle2'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    @staticmethod
    def create_mem_lyr(lyr_name):
        """ Create temporary 'memory' layer to store results.
        :param lyr_name: string, layer name
        """
        mlyr = QgsVectorLayer('Polygon?crs=epsg:4326', lyr_name, 'memory')
        prov = mlyr.dataProvider()
        mlyr.startEditing()
        prov.addAttributes([QgsField("PNAME", QVariant.String)])
        mlyr.commitChanges()
        QgsProject.instance().addMapLayer(mlyr)

    def add_feature_to_layer(self, boundary):
        """ Add feature to layer
        :param: boundary: list, list of QgsPoint objects
        """
        out_lyr = QgsVectorLayer('Polygon?crs=epsg:4326', self.mlyr_name, 'memory')
        out_lyr = self.iface.activeLayer()
        out_lyr.startEditing()
        out_prov = out_lyr.dataProvider()
        feat = QgsFeature()
        feat.setGeometry(QgsGeometry.fromPolygonXY([boundary]))
        feat.setAttributes([self.polygon_name])
        out_prov.addFeatures([feat])
        out_lyr.commitChanges()
        out_lyr.updateExtents()
        self.iface.mapCanvas().setExtent(out_lyr.extent())
        self.iface.mapCanvas().refresh()

    def circ_center_def(self):
        """ Enable/disable editing of circle center definition """
        if self.dlg.checkBoxCenterDef.isChecked():
            self.dlg.labelCenterBrng.setEnabled(True)
            self.dlg.lineEditCenterBrng.setEnabled(True)
            self.dlg.labelCenterDist.setEnabled(True)
            self.dlg.lineEditCenterDist.setEnabled(True)
            self.dlg.comboBoxCenterDistUOM.setEnabled(True)
            self.dlg.comboBoxCenterDistUOM.setCurrentIndex(0)
            self.dlg.labelRefMagVar.setEnabled(True)
            self.dlg.lineEditRefMagVar.setEnabled(True)
        else:
            self.dlg.labelCenterBrng.setEnabled(False)
            self.dlg.lineEditCenterBrng.setEnabled(False)
            self.dlg.labelCenterDist.setEnabled(False)
            self.dlg.lineEditCenterDist.setEnabled(False)
            self.dlg.comboBoxCenterDistUOM.setEnabled(False)
            self.dlg.labelRefMagVar.setEnabled(False)
            self.dlg.lineEditRefMagVar.setEnabled(False)
        return

    def get_center_dist_uom(self):
        """ Returns distance to center unit of measure """
        if self.dlg.comboBoxCenterDistUOM.currentIndex() == 0:  # m
            return ct.UOM_M
        elif self.dlg.comboBoxCenterDistUOM.currentIndex() == 1:  # km
            return ct.UOM_KM
        elif self.dlg.comboBoxCenterDistUOM.currentIndex() == 2:  # NM
            return ct.UOM_NM
        elif self.dlg.comboBoxCenterDistUOM.currentIndex() == 3:  # feet
            return ct.UOM_FEET
        elif self.dlg.comboBoxCenterDistUOM.currentIndex() == 4:  # SM
            return ct.UOM_SM

    def get_radius_uom(self):
        """ Returns radius unit of measure """
        if self.dlg.comboBoxRadiusUOM.currentIndex() == 0:  # m
            return ct.UOM_M
        elif self.dlg.comboBoxRadiusUOM.currentIndex() == 1:  # km
            return ct.UOM_KM
        elif self.dlg.comboBoxRadiusUOM.currentIndex() == 2:  # NM
            return ct.UOM_NM
        elif self.dlg.comboBoxRadiusUOM.currentIndex() == 3:  # feet
            return ct.UOM_FEET
        elif self.dlg.comboBoxRadiusUOM.currentIndex() == 4:  # SM
            return ct.UOM_SM

    def check_input(self):
        """ Checks if input data is correct """
        err_msg = ''
        check_result = True

        lat_src = self.dlg.lineEditRefLat.text()
        lon_src = self.dlg.lineEditRefLon.text()
        radius_src = self.dlg.lineEditRadius.text()

        # Ref point - against circle center will be calculated
        ref_point = ct.CoordinatesPair(lat_src, lon_src)

        if ref_point.is_valid is False:
            check_result = False
            err_msg = ref_point.err_msg

        if self.dlg.checkBoxCenterDef.isChecked():
            # Check magnetic variation
            mag_var_src = self.dlg.lineEditRefMagVar.text()
            mag_var = ct.MagVar(mag_var_src)
            if mag_var.is_valid is False:
                check_result = False
                err_msg += 'Magnetic variation error!\n'

            # Check bearing to circle center
            brng_src = self.dlg.lineEditCenterBrng.text()
            brng = ct.Bearing(brng_src)
            if brng.is_valid is False:
                check_result = False
                err_msg += 'Bearing error!\n'

            # Check distance to center
            center_dist_src = self.dlg.lineEditCenterDist.text()
            if center_dist_src == '':
                check_result = False
                err_msg += 'Enter distance from reference point to center!\n'
            else:
                center_dist_check = ct.check_distance2(center_dist_src)
                if center_dist_check == ct.NOT_VALID:
                    check_result = False
                    err_msg += 'Distance to center error!\n'

        if radius_src == '':
            check_result = False
            err_msg += 'Enter radius!\n'
        else:
            dist_check = ct.check_distance2(radius_src)
            if dist_check == ct.NOT_VALID:
                check_result = False
                err_msg += 'Distance error!'
            else:
                self.radius_m = ct.convert_distance(dist_check, self.get_radius_uom(), ct.UOM_M)

        if check_result is False:
            QMessageBox.critical(w, "Message", err_msg)
        else:
            if self.dlg.checkBoxCenterDef.isChecked():  # Calculate circle center
                # Calculate true bearing
                brng.calc_tbrng(mag_var.dd_value)
                # Calculate distance to center in m
                dist_m = ct.to_meters(center_dist_check, self.get_center_dist_uom())
                # Calculate latitude and longitude of circle center
                lat_center, lon_center = ct.vincenty_direct_solution(ref_point.dd_lat,
                                                                     ref_point.dd_lon,
                                                                     brng.dd_tbrng,
                                                                     dist_m,
                                                                     ct.WGS84_A,
                                                                     ct.WGS84_B,
                                                                     ct.WGS84_F)
                self.circ_center = ct.CoordinatesPair(lat_center, lon_center)
            elif not self.dlg.checkBoxCenterDef.isChecked():
                self.circ_center = ref_point

        return check_result

    def add_circle(self):
        if self.check_input():

            # Create circle polygon
            poly_vertices = []
            for i in range(0, 360):
                vertex_lat, vertex_lon = ct.vincenty_direct_solution(self.circ_center.dd_lat,
                                                                     self.circ_center.dd_lon,
                                                                     i, self.radius_m,
                                                                     ct.WGS84_A,
                                                                     ct.WGS84_B,
                                                                     ct.WGS84_F)

                poly_vertex = QgsPointXY(vertex_lon, vertex_lat)
                poly_vertices.append(poly_vertex)

            layers = QgsProject.instance().layerTreeRoot().children()
            layers_list = []  # List of layers in current (opened) QGIS project
            for layer in layers:
                layers_list.append(layer.name())

            if self.mlyr_name == '':
                self.mlyr_name = ct.get_tmp_name()
            self.polygon_name = self.dlg.lineEditPolyName.text()

            if self.mlyr_name not in layers_list:
                self.create_mem_lyr(self.mlyr_name)
                self.add_feature_to_layer(poly_vertices)
            else:
                self.add_feature_to_layer(poly_vertices)

    def run(self):
        """Run method that performs all the real work"""
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
